name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_ID = "Ov23liFEM7BfR3xD3svz" # 你的 GitHub OAuth App 的 Client ID
GITHUB_OWNER = "bingo0621"          # 你的 GitHub 用户名
GITHUB_REPO = "NavSphere"           # 你的 GitHub 仓库名
GITHUB_BRANCH = "main"              # 你的 GitHub 分支名
NEXTAUTH_URL = "https://navsphere-bingo.pages.dev/api/auth" # Cloudflare Pages 域名 + /api/auth
NEXT_PUBLIC_API_URL = "https://navsphere-bingo.pages.dev/"  # Cloudflare Pages 域名
NEXT_PUBLIC_SITE_URL = "https://navsphere-bingo.pages.dev/" # Cloudflare Pages 域名
